### ISSUE TITLE
Better document how auth works with Docker

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/documentation#332]
We often get a question: "how to create docker container with creadentials?"
I usually refer people to the docs we have on init-file: https://memgraph.com/docs/configuration/configuration-settings#use-the-init-file-flag-with-docker
But, setting the username and password via env is much easier: https://memgraph.com/docs/configuration/configuration-settings#environment-variables
We should document that the following Docker Compose creates a user, because it's not clear from the Environment variables
docs that `MEMGRAPH_USER` and `MEMGRAPH_PASSWORD` is not only for auth, but also for creating user, especially when having `MEMGRAPH_PASSFILE` too:

```
version: "3"
services:
  memgraph-platform:
    image: memgraph/memgraph-platform
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    environment:
      - MEMGRAPH_USER=katarina
      - MEMGRAPH_PASSWORD=pass
volumes:
  mg_lib:
  mg_log:
  mg_etc:
```

I think we should come up with a couple of examples when to use which approach and how to correctly set up auth with Docker (Compose) or without it.
