### ISSUE TITLE
Docker compose documentation

### ISSUE THREAD

**Issue by Eclegv** [memgraph/documentation#597]
From the user's perspective, the page [Docker Compose](https://memgraph.com/docs/getting-started/install-memgraph/docker-compose) lacks a part on the healthcheck:

- Which could be useful when we work with github actions and want to run commands directly when the container is up
- Which could prevent hours of not understanding why the container send back connection refused

And we could provide an example like :
<pre>healthcheck:
   test: echo "RETURN 0;" | mgconsole || exit 1
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 0s
</pre>

**Comment by matea16** [comment]
Hi @Eclegv, thank you for opening the issue! Just for the context, this is related to the [Discord conversation](https://discord.com/channels/842007348272169002/890969266600423504/1217983986694094939)

**Comment by kgolubic** [comment]
Thank you @Eclegv! 

I just need to see which approach we would use, the Inline string command from @Eclegv or Array with `CMD-SHELL` that would look something like this:

```
healthcheck:
  test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole || exit 1"]
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 0s
```
