### ISSUE TITLE
Document environment variables 

### ISSUE THREAD

**Issue by matea16** [memgraph/documentation#640]
There's missing info on usage of  `MEMGRAPH_USER` and `MEMGRAPH_PASSWORD` env vars

`MEMGRAPH_USER` and `MEMGRAPH_PASSWORD` serve the purpose of creating a user if such doesn't already exist in the database. Example of usage:
```
version: "3"
 
services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: memgraph-mage
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    command: ["--log-level=TRACE"]
    environment:
      - MEMGRAPH_USER=matea
      - MEMGRAPH_PASSWORD=0000
 
  lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "3000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

volumes:
  mg_lib:
  mg_log:
  mg_etc:
```

**!NOTE:**
this works:
```
environment:
      - MEMGRAPH_USER=matea
      - MEMGRAPH_PASSWORD=0000
```

but the same env with spaces doesn't work:
```
environment:
      - MEMGRAPH_USER = matea
      - MEMGRAPH_PASSWORD = 0000
```
